### ISSUE TITLE
Flexo The Robot

### ISSUE THREAD

**Issue by ThatGamerBlue** [runelite-extended/runelite#1291]
This is a meta thread about flexo, see label meta for more information.

We have a few decisions to make about flexo at the moment, involving implementation and the current state of it in this repository.

### In this repository
Should we:

1. Keep it in this repository, therefore in the launcher distribution
2. Move it to a separate repository under the runelite-extended namespace as an external plugin
3. Same as 2 but under a different namespace.

This would be to avoid confusion about what flexo is, and why is it in the client when its use is for things we don't endorse. See: discord search for flexo (ignore bot results). Most people are either running the command to find out or asking about what it is.

### As a... thing
We need to figure out what we want to do with flexo as a thing, what features are prioritized, what is less important, what bugs are there and so on. I see two ways we could go about this, depending on the result of the first question. We could:

1. Create a GitHub [project] for flexo, containing issues and feature requests
2. Use the GitHub issue tracker in another repository.

Your opinions on this should not sway your answer to the first question, we will be implementing one of these depending on the result.

[project]: https://github.com/runelite-extended/runelite/projects

**Comment by zeruth** [comment]
I've always been a huge supporter of having it in the main project. It IS a core functionality of our client, even if it isn't strictly endorsed. I also like how every user has access to those classes. Not that they do, but if they check classes, I would want every one of our users to be flagged for flexo, not just the ones using it.

**Comment by ThatGamerBlue** [comment]
> Not that they do, but if they check classes, I would want every one of our users to be flagged for flexo, not just the ones using it.
I would personally say everyone getting flagged for it even if they don't use it is a bad idea, particularly if they're not using it in any way.

**Comment by zeruth** [comment]
They wont ban everyone for having access to the class unless they can prove they are using it. restricting it to only people using it, gives them that advantage, and I won't allow that.

**Comment by Lucwousin** [comment]
So instead of taking your own risk of getting banned you pull people in who wouldn't be risking anything otherwise?

STRONG disagree.

It hasn't really been a core piece of the project either (everything works without it).

**Comment by zeruth** [comment]
no, its minimizing risk, while applying no risk to everyone else. again, THEY WONT BAN WITHOUT ACTUAL PROOF.

**Comment by Crystalknoct** [comment]
As jagex has said in the past as long as its human input they really dont care much.

**Comment by zeruth** [comment]
If you don't want flexo in your project, go ahead and 
![image](https://user-images.githubusercontent.com/2943260/62824955-1edd5b80-bb72-11e9-83da-9bcda90b031c.png)

**Comment by Owain94** [comment]
I agree with @Lucwousin, the core isn’t needed and jagex won’t ban based on classes anyways. You can use a cheat client to play normally and you won’t get banned.

One of the most popular zulrah helpers is on a botting client, and people don’t get banned using that helper, since they don’t use automation. 

Imo flexo should just be an external plugin provided but not supported by us.

We don’t support cheating so we shouldn’t include it in the core of the project. But just provide an external plugin with a warning that external plugin can resolve in a ban especially when they include automation.

People dislike our client already, have build in automation doesn’t help with that reputation. Especially since it can easily be an external plugin.

**Comment by zeruth** [comment]
lol, it doesn't matter, people will STILL message about it, people ALREADY KNOW it exists. Hell there is a whole other discord around it. Making it an external plugin won't make it any less noticeable, and will require another dependency for external plugins. 

1: We don't have restrictions, that's the whole point of the project.
2: I don't really care if people dislike us over petty opinionated things.
3. We have plenty of actually important problems in the project, and should probably be attending those instead of making more out of thin air.

**Comment by Owain94** [comment]
Not having the restrictions that the runelite devs add is a whole different thing than adding support for botting and cheating imo

Having it in the core looks like we support automation and cheating.

I agree that we have more issues that may or may not be more important but that doesn’t mean we can ignore other things.

This is my opinion but it doesn’t make us look good imo

**Comment by zeruth** [comment]
It will be made external after assessing the poll. (before it was memed). As always we will not offer direct support for it in our discord. It will most likely be made into it's own repo where you are free to PR etc. We just don't want it in the main project, so users can choose for themselves whether or not they have access to it.
